<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\Salary\" />
    <Folder Include="Configurations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Blazored.Toast" Version="4.2.1" />
    <PackageReference Include="DevExpress.Blazor" Version="23.2.6" />
    <PackageReference Include="Faso.Blazor.SpinKit" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HNOne.Common\HNOne.Common.csproj" />
    <ProjectReference Include="..\HNOne.Model\HNOne.Model.csproj" />
  </ItemGroup>

</Project>
